### ISSUE TITLE
Generation error with Flutter 2.0

### ISSUE THREAD

**Issue by wilkomanger** [lejard-h/chopper#210]
Hi, when running `flutter pub run build_runner build`, this error appears:

```
[SEVERE] chopper_generator:chopper_generator on test/key_input_widget_test.dart:

NoSuchMethodError: The getter 'flow' was called on null.
Receiver: null
Tried calling: flow
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      ResolverVisitor.startNullAwarePropertyAccess (package:analyzer/src/generated/resolver.dart:805:23)
#2      ResolverVisitor.visitPropertyAccess (package:analyzer/src/generated/resolver.dart:1776:5)
#3      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8390:49)
#4      BinaryExpressionResolver._resolveEqual (package:analyzer/src/dart/resolver/binary_expression_resolver.dart:111:10)
#5      BinaryExpressionResolver.resolve (package:analyzer/src/dart/resolver/binary_expression_resolver.dart:58:7)
#6      ResolverVisitor.visitBinaryExpression (package:analyzer/src/generated/resolver.dart:944:31)
#7      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:956:49)
#8      ResolverVisitor.visitAssertInitializer (package:analyzer/src/generated/resolver.dart:903:21)
#9      AssertInitializerImpl.accept (package:analyzer/src/dart/ast/ast.dart:519:49)
#10     AstResolver.resolve (package:analyzer/src/summary2/ast_resolver.dart:85:10)
#11     ConstructorInitializerResolver._initializers (package:analyzer/src/summary2/constructor_initializer_resolver.dart:68:20)
#12     ConstructorInitializerResolver._constructor (package:analyzer/src/summary2/constructor_initializer_resolver.dart:54:5)
#13     ConstructorInitializerResolver.resolve (package:analyzer/src/summary2/constructor_initializer_resolver.dart:31:11)
#14     LibraryBuilder.resolveConstructors (package:analyzer/src/summary2/library_builder.dart:240:53)
#15     Linker._resolveConstructors (package:analyzer/src/summary2/link.dart:210:15)
#16     Linker._buildOutlines (package:analyzer/src/summary2/link.dart:95:5)
#17     Linker.link (package:analyzer/src/summary2/link.dart:76:5)
#18     link (package:analyzer/src/summary2/link.dart:32:10)
#19     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:215:24)
#20     LibraryContext.load2.loadBundle.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:123:26)
#21     SetMixin.forEach (dart:collection/set.dart:142:30)
#22     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:122:32)
#23     LibraryContext.load2.loadBundle.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:123:26)
#24     SetMixin.forEach (dart:collection/set.dart:142:30)
#25     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:122:32)
#26     LibraryContext.load2.loadBundle.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:123:26)
#27     SetMixin.forEach (dart:collection/set.dart:142:30)
#28     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:122:32)
#29     LibraryContext.load2.loadBundle.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:123:26)
#30     SetMixin.forEach (dart:collection/set.dart:142:30)
#31     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:122:32)
#32     LibraryContext.load2.loadBundle.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:123:26)
#33     SetMixin.forEach (dart:collection/set.dart:142:30)
#34     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:122:32)
#35     LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:262:17)
#36     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#37     LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:260:12)
#38     AnalysisDriver._createLibraryContext.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1550:25)
#39     _rootRun (dart:async/zone.dart:1354:13)
#40     _CustomZone.run (dart:async/zone.dart:1258:19)
#41     _runZoned (dart:async/zone.dart:1788:10)
#42     runZoned (dart:async/zone.dart:1710:10)
#43     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#44     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1536:33)
#45     AnalysisDriver._computeUnitElement.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1464:28)
#46     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#47     AnalysisDriver._computeUnitElement (package:analyzer/src/dart/analysis/driver.dart:1462:20)
#48     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1020:34)
#49     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2013:24)
<asynchronous suspension>
```
I suspect something needs to be changed in the Chopper generator regarding Flutter 2.0?

**Comment by stewemetal** [comment]
Hi,

We are actively working on updating chopper to be compatible with Flutter 2. See #212 .

We'll get back to this issue if it still persists after the update is published. 😉

Thank you for your patience!

**Comment by wilkomanger** [comment]
Great, thanks!

**Comment by fryette** [comment]
@stewemetal  is it possible to publish a new version?

**Comment by stewemetal** [comment]
We're right on track with the new release, just a few minor things left for us to settle on!

Track our progress here: #219 

4.0.0 is right around the corner!

**Comment by JEuler** [comment]
https://pub.dev/packages/chopper/versions/4.0.0-nullsafety.1
