### ISSUE TITLE
Large auth token for header error for ChopperClient

### ISSUE THREAD

**Issue by Chrisphine10** [lejard-h/chopper#385]
## Steps to Reproduce

1. Create ChopperClient for API POST call with interceptors and the chopper inbuilt jsonconverter.
2. Add an auth interceptor with the token header. 
3. Make sure the token header is larger than 200 letters.

**Expected results:** 
1. I expected the api to be invoked. 

**Actual results:** 
I got an error with the converter saying that the data types are not compatible. 

<details>
<summary>Code sample</summary>
```
register(UserCreate user) async {
    final client = ChopperClient(
        baseUrl: API,
        services: [AccountApiService.create()],
        interceptors: [headerInterceptor],
        converter: JsonConverter());
    final responseData = client.getService<AccountApiService>();
    var response = await responseData.register(user);
    return response;
  }

Future<Request> headerInterceptor(Request request) async {
    final headers = Map<String, String>.from(request.headers);
    this.token = GetStorage().read('token');
    headers['accept'] = '*/*';
    headers['Content-Type'] = ApiConstants.contentType;
    headers['Authorization'] = token;
    request = request.copyWith(headers: headers);
    return request;
  }
```

```
```

</details>

<details>
  <summary>Logs</summary>

> E/flutter ( 5213): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'String' is not a subtype of type 'UserCreate?'
> E/flutter ( 5213): #0      JsonConverter.decodeJson (package:chopper/src/interceptor.dart:272:46)
> E/flutter ( 5213): <asynchronous suspension>
> E/flutter ( 5213): #1      JsonConverter.convertResponse (package:chopper/src/interceptor.dart:279:8)
> E/flutter ( 5213): <asynchronous suspension>
> E/flutter ( 5213): #2      ChopperClient._decodeResponse (package:chopper/src/base.dart:186:7)
> E/flutter ( 5213): <asynchronous suspension>
> E/flutter ( 5213): #3      ChopperClient._handleSuccessResponse (package:chopper/src/base.dart:254:11)
> E/flutter ( 5213): <asynchronous suspension>
> E/flutter ( 5213): #4      ChopperClient.send (package:chopper/src/base.dart:324:11)
> E/flutter ( 5213): <asynchronous suspension>
> E/flutter ( 5213): #5      UserRest.register (package:fairfare/resource/chopper_service/user/user_rest.dart:39:20)
> E/flutter ( 5213): <asynchronous suspension>
> E/flutter ( 5213): #6      AuthController.register (package:fairfare/controller/auth_controller.dart:41:25)
> E/flutter ( 5213): <asynchronous suspension>
> E/flutter ( 5213):

```
Output too big.
```

```
$ dart analyze
Analyzing fairfare mobile flutter...

   info • lib\controller\register_controller.dart:1:8 • Unused import: 'package:fairfare/models/user/user.dart'. Try removing the import       
          directive. • unused_import
   info • lib\controller\register_controller.dart:2:8 • Unused import: 'package:fairfare/sharedPreferences.dart'. Try removing the import      
          directive. • unused_import
   info • lib\location_resources.dart:9:20 • The declaration '_determinePosition' isn't referenced. Try removing the declaration of
          '_determinePosition'. • unused_element
   info • lib\models\amazon_gift_card\amazon_gift_card.g.dart:9:26 • Name non-constant identifiers using lowerCamelCase. •
          non_constant_identifier_names
   info • lib\models\amazon_gift_card\amazon_gift_card.g.dart:23:22 • Name non-constant identifiers using lowerCamelCase. •
          non_constant_identifier_names
   info • lib\models\card\card.g.dart:9:15 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\card\card.g.dart:28:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\feedback\feedback.g.dart:9:16 • The declaration '_$FeedBackCreateFromJson' isn't referenced. Try removing the declaration 
          of '_$FeedBackCreateFromJson'. • unused_element
   info • lib\models\feedback\feedback.g.dart:23:13 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names      
   info • lib\models\feedback\feedback.g.dart:30:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names      
   info • lib\models\gift_card\card.g.dart:9:16 • The declaration '_$GiftCardCreateFromJson' isn't referenced. Try removing the declaration of 
          '_$GiftCardCreateFromJson'. • unused_element
   info • lib\models\gift_card\card.g.dart:27:13 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\gift_card\card.g.dart:36:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\lime\lime.g.dart:9:23 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\lime\lime.g.dart:28:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\lime\lime.g.dart:45:23 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\lime\lime.g.dart:56:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\lime\lime.g.dart:67:13 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\lime\lime.g.dart:74:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\lime\lime.g.dart:81:13 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\lime\lime.g.dart:88:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\lime\lime.g.dart:95:13 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\lime\lime.g.dart:100:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\lime\lime.g.dart:106:30 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\lime\lime.g.dart:120:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\lime\lime.g.dart:128:20 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\lime\lime.g.dart:136:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\location\location.g.dart:9:16 • The declaration '_$LocationCreateFromJson' isn't referenced. Try removing the declaration 
          of '_$LocationCreateFromJson'. • unused_element
   info • lib\models\location\location.g.dart:27:13 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names      
   info • lib\models\location\location.g.dart:36:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names      
   info • lib\models\location\location.g.dart:46:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names      
   info • lib\models\location\location.g.dart:55:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names      
   info • lib\models\preference\preference.g.dart:9:15 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names   
   info • lib\models\preference\preference.g.dart:15:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names  
   info • lib\models\referral\referral.g.dart:9:13 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names       
   info • lib\models\referral\referral.g.dart:17:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names      
   info • lib\models\service_provider\service_provider.g.dart:9:28 • The declaration '_$SavedServiceProviderCreateFromJson' isn't referenced.  
          Try removing the declaration of '_$SavedServiceProviderCreateFromJson'. • unused_element
   info • lib\models\service_provider\service_provider.g.dart:32:20 • Name non-constant identifiers using lowerCamelCase. •
          non_constant_identifier_names
   info • lib\models\service_provider\service_provider.g.dart:40:22 • Name non-constant identifiers using lowerCamelCase. •
          non_constant_identifier_names
   info • lib\models\service_provider\service_provider.g.dart:48:25 • Name non-constant identifiers using lowerCamelCase. •
          non_constant_identifier_names
   info • lib\models\service_provider\service_provider.g.dart:62:22 • Name non-constant identifiers using lowerCamelCase. •
          non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:9:26 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:16:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:23:27 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:40:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:53:16 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:71:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:86:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:99:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:113:21 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:121:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:129:21 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:142:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:150:25 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:158:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:166:25 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:181:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:193:5 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:201:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:210:34 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:219:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:228:30 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:245:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:258:15 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:267:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:276:16 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:284:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:292:13 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\uber\uber.g.dart:311:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\user\user.g.dart:9:9 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\models\user\user.g.dart:31:22 • Name non-constant identifiers using lowerCamelCase. • non_constant_identifier_names
   info • lib\sharedPreferences.dart:1:8 • Unused import: 'package:get/get.dart'. Try removing the import directive. • unused_import
   info • lib\sharedPreferences.dart:5:16 • The value of the field '_authDetails' isn't used. Try removing the field, or using it. •
          unused_field
   info • lib\utils\local_string.dart:28:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map
   info • lib\utils\local_string.dart:42:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map
   info • lib\utils\local_string.dart:83:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map
   info • lib\utils\local_string.dart:84:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map
   info • lib\utils\local_string.dart:85:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map
   info • lib\utils\local_string.dart:86:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map
   info • lib\utils\local_string.dart:108:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map
   info • lib\utils\local_string.dart:164:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map
   info • lib\utils\local_string.dart:165:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map
   info • lib\utils\local_string.dart:192:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map
   info • lib\utils\local_string.dart:206:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map
   info • lib\utils\local_string.dart:247:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map
   info • lib\utils\local_string.dart:248:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map
   info • lib\utils\local_string.dart:249:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map
   info • lib\utils\local_string.dart:250:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map
   info • lib\utils\local_string.dart:272:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map
   info • lib\utils\local_string.dart:328:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map
   info • lib\utils\local_string.dart:329:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map
   info • lib\utils\local_string.dart:356:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map
   info • lib\utils\local_string.dart:370:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map
   info • lib\utils\local_string.dart:411:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map
   info • lib\utils\local_string.dart:412:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map
   info • lib\utils\local_string.dart:413:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map
   info • lib\utils\local_string.dart:414:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map
   info • lib\utils\local_string.dart:436:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map
   info • lib\utils\local_string.dart:492:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map
   info • lib\utils\local_string.dart:493:11 • Two keys in a map literal shouldn't be equal. Change or remove the duplicate key. •
          equal_keys_in_map

100 issues found.
```

```
$ dart --version
Dart SDK version: 2.19.0-146.2.beta (beta) (Tue Sep 20 10:30:48 2022 +0000) on "windows_x64"
```

</details>

**Comment by techouse** [comment]
Could you please clean up your message above, as it's impossible to read?

Also, have you tried creating your own authenticator by extending the [Authenticator](https://github.com/lejard-h/chopper/blob/develop/chopper/lib/src/authenticator.dart)? You can then pass it in the [ChopperClient.authenticator](https://github.com/lejard-h/chopper/blob/develop/chopper/lib/src/base.dart#L43) constructor parameter.

```dart
final client = ChopperClient(
  // ... stuff
  authenticator: MyAuthenticator(),
);
```
