### ISSUE TITLE
Unhandled Exception: type 'Response<dynamic>' is not a subtype of type 'Response<List<Message>>' in type cast

### ISSUE THREAD

**Issue by tobybonhof** [lejard-h/chopper#94]
Im using chopper with jaguar converter i litterally copied the code in my project but im getting

```
Unhandled Exception: type 'Response<dynamic>' is not a subtype of type 'Response<List<Message>>' in type cast
```
Full stack:

```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: type 'Response<dynamic>' is not a subtype of type 'Response<List<Message>>' in type cast
#0      JsonConverter.convertResponse (package:chopper/src/interceptor.dart:178:28)
#1      JaguarConverter.convertResponse (package:flutter_app/base/api/jaguar/jaguar_converter.dart:38:27)
#2      ChopperClient._decodeResponse (package:chopper/src/base.dart:111:29)
<asynchronous suspension>
#3      ChopperClient._handleSuccessResponse (package:chopper/src/base.dart:185:17)
<asynchronous suspension>
#4      ChopperClient.send (package:chopper/src/base.dart:233:19)
<asynchronous suspension>
#5      _$GeeksAdminApi.getMessages (package:flutter_app/core/api/service/geeks_admin_api.chopper.dart:20:19)
#6      GetMessages.call (package:flutter_app/core/api/call/get_messages.dart:24:16)
#7      Call.stream (package:flutter_app/core/api/call/call.dart:43:28)
<asynchronous suspension>
#8      Call.execute (package:flutter_app/core/api/call/call.dart:37:10)
#9      Me<…>

```

Api:
```
@ChopperApi(baseUrl: ApiRoutes.ADMIN_VERSION)
abstract class AdminApi extends BaseApi {

  static AdminApi _api = _init();
  static AdminApi _init() {
    final client = ChopperClient(
        baseUrl: ApiRoutes.ADMIN_BASE_URL,
        services: [_$GeeksAdminApi()],
        converter: JaguarConverter(),
        interceptors: [AdminInterceptor(), CurlInterceptor()]
    );
    return _$AdminApi(client);
  }

  static AdminApi getInstance() {
    return _api;
  }

  @Get(path: ApiRoutes.ADMIN_MESSAGES)
  Future<Response<List<Message>>> getMessages();

  @Get(path: "/reports")
  Future<Response<String>> getReports();
}

```
Message:
```
import 'package:jaguar_serializer/jaguar_serializer.dart';


part 'message.jser.dart';

class Message {
  String title;
  String message;
  int age;
}

@GenSerializer()
class MessageSerializer extends Serializer<Message> with _$MessageSerializer {
}

```

JaguarConverter
```
/// Map all your serializer in a repository
final repository = SerializerRepoImpl(serializers: [
  MessageSerializer()
]);

class JaguarConverter extends JsonConverter {
  dynamic _decode<Item>(entity) {
    /// handle case when we want to access to Map<String, dynamic> directly
    /// getResource or getMapResource
    /// Avoid dynamic or unconverted value, this could lead to several issues
    ///
    ///
    print(entity);
    if (entity is Item) return entity;

    final serializer = repository.getByType<Item>(
      Item,
    );

    /// throw serializer not found error;
    if (serializer == null) return null;

    if (entity is Map) return serializer.fromMap(entity);

    if (entity is List) return serializer.fromList(entity.cast<Map>());

    return entity;
  }

  @override
  Response<ResultType> convertResponse<ResultType, Item>(Response response) {
    // use [JsonConverter] to decode json
    print(response);
    final jsonRes = super.convertResponse<ResultType, Item>(response);

    return jsonRes.replace<ResultType>(
      body: _decode<Item>(jsonRes.body),
    );
  }

  @override
  Request convertRequest(Request request) =>
      super.convertRequest(
        request.replace(
          body: repository.to(request.body),
        ),
      );


  @override
  Response convertError<ResultType, ItemType>(Response response) {
    // use [JsonConverter] to decode json
//    final jsonRes = super.convertError(response);
//    return jsonRes.replace(body: _errorSerializer.fromMap(jsonRes.body));
    return response;
  }
}

```

**Comment by HuguesBadzou** [comment]
Hey, use json serializer it works better. I had the same issue with Jaguar Serializer I've just let to use Json Serializable.

**Comment by lejard-h** [comment]
I won't do the support for jaguar_serializer anymore, please use json_serializable or built_value

**Comment by PalakSDarji** [comment]
I am having the same issue with json_serializable as well. Do you guys have something to help with?
