### ISSUE TITLE
error converter implementation not working

### ISSUE THREAD

**Issue by shaikhriyaz434** [lejard-h/chopper#95]
```
/flutter (15477): INFO: 2019-09-14 22:30:48.013882: {"error":{"statusCode":404,"name":"Error","message":"Cannot GET /a/bmsUsers","status":404,"stack":"Error: Cannot GET /a/bmsUsers\n    at raiseUrlNotFoundError (/usr/src/app/node_modules/loopback/server/middleware/url-not-found.js:21:17)\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)\n    at /usr/src/app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)\n    at /usr/src/app/node_modules/express/lib/router/index.js:635:15\n    at next (/usr/src/app/node_modules/express/lib/router/index.js:260:14)\n    at Function.handle (/usr/src/app/node_modules/express/lib/router/index.js:174:3)\n    at router (/usr/src/app/node_modules/express/lib/router/index.js:47:12)\n    at Layer.handle
I/flutter (15477): INFO: 2019-09-14 22:30:48.014156: --> END GET (1472-byte body)
E/flutter (15477): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Instance of 'Response<dynamic>'
E/flutter (15477): #0      ChopperClient.send (package:chopper/src/base.dart:193:7)
E/flutter (15477): <asynchronous suspension>
E/flutter (15477): #1      _$UserApiService.getUsers (package:bms_app/Data/API/User/UserApiService.chopper.dart:20:19)``
```

**Comment by lejard-h** [comment]
Hello @shaikhriyaz434 
Can I have more information ? code exemple ? what did you try ?
